name: Deploy Static Site to GitHub Pages

on:
  # Trigger on pushes to main branch
  push:
    branches: [ main ]
    paths:
      - 'site/**'
      - '.github/workflows/pages-deploy.yml'
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deploy static files directly
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify site directory exists
        run: |
          if [ ! -d "./site" ]; then
            echo "Error: ./site directory not found!"
            exit 1
          fi
          echo "Site directory found with $(find ./site -type f | wc -l) files"
          
      - name: List site contents
        run: |
          echo "Site directory contents:"
          ls -la ./site/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4