name: Deploy Static Site to GitHub Pages

on:
  # Allow manual trigger only
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deploy static files directly
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify site directory exists
        run: |
          if [ ! -d "./front-end/out" ]; then
            echo "Error: ./front-end/out directory not found!"
            exit 1
          fi
          echo "Site directory found with $(find ./front-end/out -type f | wc -l) files"

      - name: List site contents
        run: |
          echo "Site directory contents:"
          ls -la ./front-end/out/

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './front-end/out/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4